<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('books')->insert([
            // Technology Books
            [
                'title' => 'The Innovators',
                'author' => 'Walter Isaacson',
                'category_id' => 1,
                'published_year' => 2014,
                'copies_available' => 5,
                'cover_image' => 'images/71zcV2aQrQL._SY425_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Clean Code',
                'author' => 'Robert C. Martin',
                'category_id' => 1,
                'published_year' => 2008,
                'copies_available' => 3,
                'cover_image' => 'images/51E2055ZGUL._SY385_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Pragmatic Programmer',
                'author' => 'Andrew Hunt & David Thomas',
                'category_id' => 1,
                'published_year' => 1999,
                'copies_available' => 2,
                'cover_image' => 'images/510NRcB7AAL._SY445_SX342_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Mythical Man-Month',
                'author' => 'Frederick P. Brooks Jr.',
                'category_id' => 1,
                'published_year' => 1975,
                'copies_available' => 3,
                'cover_image' => 'images/51TG5T+dd7L._SY445_SX342_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Artificial Intelligence: A Guide for Thinking Humans',
                'author' => 'Melanie Mitchell',
                'category_id' => 1,
                'published_year' => 2019,
                'copies_available' => 5,
                'cover_image' => 'images/71550omTRxL._SY425_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Health & Wellness Books
            [
                'title' => 'The 4-Hour Body',
                'author' => 'Tim Ferriss',
                'category_id' => 2,
                'published_year' => 2010,
                'copies_available' => 4,
                'cover_image' => 'images/41e4aOKoLLL._SY445_SX342_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Atomic Habits',
                'author' => 'James Clear',
                'category_id' => 2,
                'published_year' => 2018,
                'copies_available' => 6,
                'cover_image' => 'images/71F4+7rk2eL._SX342_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Why We Sleep',
                'author' => 'Matthew Walker',
                'category_id' => 2,
                'published_year' => 2017,
                'copies_available' => 5,
                'cover_image' => 'images/418OQ6gWywL._SY445_SX342_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Blue Zones: 9 Lessons for Living Longer',
                'author' => 'Dan Buettner',
                'category_id' => 2,
                'published_year' => 2012,
                'copies_available' => 5,
                'cover_image' => 'images/71S7ldYU8TL._SY425_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Obesity Code',
                'author' => 'Dr. Jason Fung',
                'category_id' => 2,
                'published_year' => 2016,
                'copies_available' => 3,
                'cover_image' => 'images/71SV8dsQchL._SX342_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            

            // Fashion Books
            [
                'title' => 'The Little Dictionary of Fashion',
                'author' => 'Christian Dior',
                'category_id' => 3,
                'published_year' => 1954,
                'copies_available' => 2,
                'cover_image' => 'images/The-little-dictionary-of-fashion.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Fashion: The Definitive History of Costume and Style',
                'author' => 'DK Publishing',
                'category_id' => 3,
                'published_year' => 2012,
                'copies_available' => 3,
                'cover_image' => 'images/71BTdibFChL._SY342_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Fashion Book',
                'author' => 'Phaidon Editors',
                'category_id' => 3,
                'published_year' => 1998,
                'copies_available' => 4,
                'cover_image' => 'images/71xwi44JpzL._SY342_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Alexander McQueen: Savage Beauty',
                'author' => 'Andrew Bolton',
                'category_id' => 3,
                'published_year' => 2011,
                'copies_available' => 2,
                'cover_image' => 'images/61VTbV47FUL._SY385_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Dior by Dior: The Autobiography of Christian Dior',
                'author' => 'Christian Dior',
                'category_id' => 3,
                'published_year' => 1957,
                'copies_available' => 2,
                'cover_image' => 'images/51n6VGykCUL._SY425_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Education Books
            [
                'title' => 'Educated',
                'author' => 'Tara Westover',
                'category_id' => 4,
                'published_year' => 2018,
                'copies_available' => 5,
                'cover_image' => 'images/81Om0n+pfyL._SY425_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Elements of Teaching',
                'author' => 'James M. Banner & Harold C. Cannon',
                'category_id' => 4,
                'published_year' => 1997,
                'copies_available' => 2,
                'cover_image' => 'images/61anlAstIbL._SY425_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Make It Stick: The Science of Successful Learning',
                'author' => 'Peter C. Brown, Henry L. Roediger III, Mark A. McDaniel',
                'category_id' => 4,
                'published_year' => 2014,
                'copies_available' => 4,
                'cover_image' => 'images/71e8wOia07L._SX342_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Smartest Kids in the World',
                'author' => 'Amanda Ripley',
                'category_id' => 4,
                'published_year' => 2013,
                'copies_available' => 4,
                'cover_image' => 'images/71AeotcoGrL._SY425_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'A Mind for Numbers',
                'author' => 'Barbara Oakley',
                'category_id' => 4,
                'published_year' => 2014,
                'copies_available' => 5,
                'cover_image' => 'images/71L3vZagdeL._SY425_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Business Books
            [
                'title' => 'Rich Dad Poor Dad',
                'author' => 'Robert Kiyosaki',
                'category_id' => 5,
                'published_year' => 1997,
                'copies_available' => 6,
                'cover_image' => 'images/81bsw6fnUiL._SY425_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Lean Startup',
                'author' => 'Eric Ries',
                'category_id' => 5,
                'published_year' => 2011,
                'copies_available' => 5,
                'cover_image' => 'images/81SrwYY-6-L._SX342_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Good to Great',
                'author' => 'Jim Collins',
                'category_id' => 5,
                'published_year' => 2001,
                'copies_available' => 3,
                'cover_image' => 'images/71LhjimPd8L._SY425_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Psychology of Money',
                'author' => 'Morgan Housel',
                'category_id' => 5,
                'published_year' => 2020,
                'copies_available' => 7,
                'cover_image' => 'images/419Tm1NaD8L._SY445_SX342_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Zero to One',
                'author' => 'Peter Thiel',
                'category_id' => 5,
                'published_year' => 2014,
                'copies_available' => 4,
                'cover_image' => 'images/71r+KgczQmL._SX342_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
